---

- name: Install PHP packages
  dnf: name="{{ item }}" state=installed
  with_items: "{{ php_packages }}"
  notify: restart webserver

- name: Enable php-fpm service
  service: name="php-fpm" state=started enabled=yes
  notify: restart webserver
