<div class='col-sm-4'>
    <p>
        Current amount: <?php echo $this->currentAmount; ?>
    </p>
</div>

<div class='col-sm-8'>
    <form method="post" action="/deposit">
        <div class='form-group row'>
            <label for='amount' class='col-xs-3 col-form-label'>Amount to deposit:</label>
            <div class='col-xs-4'>
                <input type="text" name="amount" class='form-control' />
            </div>
        </div>
        <div class='form-group row'>
            <div class='offset-xs-3 col-xs-3'>
                <input type="submit" value="Deposit" class='btn btn-primary' />
            </div>
        </div>
    </form>
</div>
